Repository kit-sdq/TimeSheetGenerator, pull requests merged in 2019-12, with the labels that each got.

#43 Fix LaTeX template
  src/main/java/io/LatexGenerator.java
  src/main/resources/MiLoG_Template.tex
Labels: enhancement

#57 Fix schema url in example global and month json
  examples/Example_global.json
  examples/Example_month.json
Labels: bug

#58 Fixed a merge resolve error
  src/main/java/checker/MiLoGChecker.java
Labels: bug, urgent

#62 Declare top level resource folder in pom
  pom.xml
Labels: bug, urgent
