Repository kit-sdq/TimeSheetGenerator, pull requests merged in 2020-01, with the labels that each got.

#67 hotfix/ExpiredSSLCertificate to master
  pom.xml
  src/main/java/checker/holiday/GermanyHolidayChecker.java
Labels: bug

#66 hotfix/ExpiredSSLCertificate to stable
  pom.xml
  src/main/java/checker/holiday/GermanyHolidayChecker.java
Labels: bug

#64 Tests for LatexGenerator
  src/test/java/io/LatexGeneratorPlaceholderTest.java
  src/test/java/io/LatexGeneratorTest.java
Labels: test

#70 Added version command to README file
  README.md
Labels: documentation

#63 Add missing documentation
  src/main/java/checker/holiday/GermanState.java
  src/main/java/main/Main.java
  src/main/java/main/UserInput.java
  src/main/java/main/UserInputFile.java
  src/main/java/main/UserInputOption.java
Labels: documentation
